language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
before_deploy: npm run build
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local_dir: dist
  skip-cleanup: true
  on:
    branch: master
